url: https://drave.dev
baseurl: "/vitrine-web/"

# Site settings
title: Drave Développement Ouvert
email: draveurs@drave.dev

description: |- #"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
    Communauté de Développement Numérique Collaboratif dédié au soutient d'un Gouvernement du Québec Ouvert

# Team names, titles and social links
people:
- name: Ricky Ng-Adam
  pic: 1
  position: Maître-Draveur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Jérémy Viau-Trudel
  pic: 2
  position: Maître-Draveur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/dravedev

# Postal address (add as many lines as necessary)
address:
  - line: Québec
  - line: Québec

# Build settings
markdown: kramdown
permalink: pretty
